version: "3.7"
services:
  jewelgenerator:
    build: ./jewelModelGenerator
    container_name: jewelgenerator
    environment:
      # IN LINUX - DISPLAY=unix$DISPLAY
      - DISPLAY=$IP:0
    env_file:
      - ./file/.env
    volumes:
      - ./jewelModelGenerator/file:/root/jewelModelGenerator/file
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    command:
      - /bin/bash
      - -c
      - '/root/jewelModelGenerator/file/docker-entrypoint.sh'
