version: "3.7"
services:
  jewelgenerator:
    build: .
    container_name: jewelgenerator
    environment:
      - DISPLAY=unix$DISPLAY
    env_file:
      - ./docker/.env
    volumes:
      - ./file:/root/jewelModelGenerator/file
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    command:
      - /bin/bash
      - -c
      - '/root/jewelModelGenerator/file/docker-entrypoint.sh'
      # - 'echo ./file/"${fileName}".jpeg && cd /root/jewelModelGenerator && ls file && ./jewel ./file/"${fileName}".jpeg ./file/"${fileName}".stl'
      
# sudo docker run --env DISPLAY=unix$DISPLAY --env fileName=A-Len -v /home/dnatuna/projects/jewelModelGenerator/file:/root/jewelModelGenerator/file -v /tmp/.X11-unix:/tmp/.X11-unix:ro jewelmodelgenerator_jewelgenerator /bin/bash -c 'ls /root/jewelModelGenerator/file && cd /root/jewelModelGenerator && ./jewel ./file/"$fileName".jpeg ./file/"$fileName".stl'

