version: "3.7"
services:
  jewelgenerator:
    build: .
    container_name: jewelgenerator
    environment:
      - DISPLAY=unix$DISPLAY
    env_file:
      - ./docker/.env
    volumes:
      - ./file:/root/jewelModelGenerator/file
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    command:
      - /bin/bash
      - -c
      - '/root/jewelModelGenerator/file/docker-entrypoint.sh'
